# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.1

test:
  stage: test
  script:
  - gem install jekyll
  - gem install jekyll jekyll-paginate
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - gem install jekyll jekyll-paginate
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
