name: Adipa Wijayathilaka
url: http://example.org
description: Software developer and jack of all trades :)

gems: [jekyll-paginate]

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments


exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
